### ISSUE TITLE
Tests are red because of typos

### ISSUE THREAD

**Issue by cclauss** [resserone13/PPEasy#8]
https://github.com/resserone13/PPEasy/actions

./Main.py:128: sheild ==> shield
./Main.py:238: transfered ==> transferred

**Comment by cclauss** [comment]
The problem with editing the file was a TabError.

./PPEasy.py:1:1: E999 TabError: inconsistent use of tabs and spaces in indentation

This happens in Python 3 when both tabs and spaces are used to indent the same line of code.  In Pythonista `Settings` (the gear ⚙️ icon), `Indentation & Coding` I turn on both `Soft Tabs (Spaces)` and `Show Mixed Indentation` and set then Tab Width to 4.  Soft Tabs should autofix TabErrors.

**Comment by resserone13** [comment]
Fixed typos
